[package]
name = "piecewise-defined-function"
version = "0.1.1"
authors = ["Armin Schäfer"]
license-file = "LICENSE"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
